.de TQ
.  br
.  ns
.  TP \\$1
..
.TH cansam 3 "" "Cancer Genome Project" "Wellcome Trust Sanger Institute"
.SH NAME
cansam \- a C++ binding for SAM/BAM files
.SH SYNOPSIS
#include <sam/alignment.h>
.PD 0
.P
// ...
.PD
.P
.BR cc " [...] " -lcansam " [...]"
.SH DESCRIPTION
The Sequence Alignment/Map (SAM) file format and its binary companion BAM
are formats for storing nucleotide sequence alignments.  They are designed
for the large volumes of short- to middling-length reads produced by
next-generation sequencing technologies.
.P
.B Cansam
is a C++ library providing classes representing the records found in
these files, facilities for reading and writing SAM and BAM files, and several
algorithms for manipulating these files, including sorting and merging.
.
.SH FILES
.TP
sam/alignment.h
.TQ
sam/header.h
The main header files.
.TP
libcansam.a
Link library; link with
.B -lcansam
to use Cansam.
.SH SEE ALSO
.IR samcat (1),
.IR samsort (1)
.TP
http://example.com/cansam/
Complete Cansam documentation.
.TP
http://samtools.sourceforge.net/
SAM file format specification.
