.TH samcat 1 "January 2012" "Cansam" "Bioinformatics tools"
.SH NAME
samcat \- concatenate and print SAM and BAM files
.\"
.\" Copyright (C) 2010-2012 Genome Research Ltd.
.\"
.\" Author: John Marshall <jm18@sanger.ac.uk>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright notice,
.\"    this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the names Genome Research Ltd and Wellcome Trust Sanger Institute
.\"    nor the names of its contributors may be used to endorse or promote
.\"    products derived from this software without specific prior written
.\"    permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY GENOME RESEARCH LTD AND ITS CONTRIBUTORS
.\" "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL GENOME RESEARCH LTD OR ITS
.\" CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
.\" EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
.\" PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
.\" OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
.\" WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
.\" OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
.\" ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.SH SYNOPSIS
.B samcat
.RB [ -bnv ]
.RB [ -f
.IR FLAGS ]
.RB [ -o
.IR FILE ]
.RB [ -O
.IR FORMAT ]
.RI [ FILE ]...
.SH DESCRIPTION
The \fBsamcat\fP utility reads files in SAM or BAM format, merges their headers,
and writes the merged headers and alignment records, sequentially from each
specified file in turn, to standard output or to a specified file.
If no input files are specified, or when \fIFILE\fP is a single hyphen ("-"),
\fBsamcat\fP reads from standard input.
.P
The following options are accepted:
.TP 4n
.B -b
Write output in BAM format.
.TP
.BI "-f " FLAGS
Display only alignment records matching \fIFLAGS\fP, as described below.
This option may be used more than once, with all
.I FLAGS
given accumulating.
.TP
.B -n
Suppress headers from the output.
.TP
.BI "-o " FILE
Write to \fIFILE\fP rather than standard output.
.TP
.BI "-O " FORMAT
Write output according to \fIFORMAT\fP, as described below.
.TP
.B -v
Display file information and statistics, on standard error.
.SS Filtering alignment records
The
.BI "-f " FLAGS
option lists combinations of flags to be included and/or excluded in the format
[[\fB+\fP]\fIinc\fP][\fB-\fIexcl\fR]
where either clause may be omitted, and the "+" introducing the \fIinc\fP
clause is also optional.
Each clause is either numeric or a set of the flag characters listed below.
.P
Each alignment record will be emitted only if it has all the flags listed in
\fIinc\fP set, and all of the flags in \fIexcl\fP not set.
.SS Output formats
By default, output is written as text in SAM format, with the \fBFLAG\fP field
displayed in decimal.
The following alternatives can be selected:
.TP 6n
.B bam
Compressed binary BAM format.
.TP
.B hex
Text SAM format, with the \fBFLAG\fP field displayed in hexadecimal.
.TP
.B text
Text SAM format, with the \fBFLAG\fP field displayed symbolically as a set of
characters representing individual bit flags:
.TS
center nokeep;
cb l .
u	Read is unmapped
f/r	Mapped to the forward (reverse) strand
U	Mate is unmapped
F/R	Mate is mapped to the forward (reverse) strand
p	Paired (lowercase "p")
P	Properly paired (capital "P")
1/2	Read is the first (second) in a pair
s	Record is not a primary alignment
q	Failed platform or vendor quality checks
d	PCR or optical duplicate
.TE
.IP
Note that this differs slightly from \fBsamtools\fP's symbolic flag notation,
which uses "f" for quality failure and doesn't explicitly denote that reads
are on the forward strand.
.TP
.B ubam
Uncompressed binary BAM format.  Sets the compression level so as to maximise
writing speed, at the cost of increased output size.
.SH SEE ALSO
.IR cansam (3),
.IR samtools (1)
.TP
http://samtools.sourceforge.net/
The SAM file format specification.
