.TH samcat 1 "" "Cancer Genome Project" "Cancer Genome Project"
.SH NAME
samcat \- concatenate and print SAM and BAM files
.SH SYNOPSIS
.BR samcat " [" -bv "] [" -o
.IR FILE "] [" FILE "]..."
.SH DESCRIPTION

.\" Probably either 4n or 9n
.TP 5n
.B -b
Write output in BAM format.
.TP
.BI "-o " FILE
Write to FILE rather than standard output.
.TP
.B -v
Display file information and statistics.
.PP
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
.SH SEE ALSO
The SAM file format specification http://samtools.sourceforge.net/
