.TH samsplit 1 "June 2011" "Cansam" "Bioinformatics tools"
.SH NAME
samsplit \- split a SAM or BAM file into separate read groups
.\"
.\" Copyright (C) 2011 Genome Research Ltd.
.\"
.\" Author: John Marshall <jm18@sanger.ac.uk>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright notice,
.\"    this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the names Genome Research Ltd and Wellcome Trust Sanger Institute
.\"    nor the names of its contributors may be used to endorse or promote
.\"    products derived from this software without specific prior written
.\"    permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY GENOME RESEARCH LTD AND ITS CONTRIBUTORS
.\" "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL GENOME RESEARCH LTD OR ITS
.\" CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
.\" EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
.\" PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
.\" OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
.\" WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
.\" OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
.\" ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.SH SYNOPSIS
.B samsplit
.RB [ -b ]
.RB [ -f
.IR FLAGS ]
.RB [ -o
.IR FILE ]
.RB [ -q
.IR NUM ]
.RB [ -z
.IR NUM ]
.I FILE
.RI [ TEMPLATE ]
.SH DESCRIPTION
The \fBsamsplit\fP utility reads one file in SAM or BAM format, and breaks it
up into several output files, one for each read group present in the input.
When \fIFILE\fP is a single hyphen ("-") or if it is absent, \fBsamsplit\fP
reads from standard input.
.P
The following options are accepted:
.TP 4n
.B -b
Write output files in BAM format.
.TP
.BI "-f " FLAGS
Emit only alignment records matching \fIFLAGS\fP, which lists flags to be
included and/or excluded in the same
[[\fB+\fP]\fIinc\fP][\fB-\fIexcl\fR]
format used by \fBsamcat\fP(1).
This option may be used more than once, with all flags given accumulating.
.TP
.BI "-o " FILE
Write all selected alignment records to \fIFILE\fP, as well as writing them
to the appropriate read group output file.
.TP
.BI "-q " NUM
Discard alignment records with mapping quality less than \fINUM\fP.
.TP
.BI "-z " NUM
Set output file compression level to \fINUM\fP.
.P
For each read group in the input, headers and those alignment records
within that read group that are selected by the various filtering options
are written to a file named according to \fITEMPLATE\fP, within which the
following escape sequences are expanded:
.TP 5n
.B %XY
The value of the read group \fB@RG\fP header's \fBXY\fP field.
.TP
.B %#
The index (starting from 1) of the read group header within all
the \fB@RG\fP headers.
.TP
.B %*
The input \fIFILE\fP basename, i.e., \fIFILE\fP with the extension and any
leading directory part removed.
.TP
.B %.
Either "sam" or "bam", as appropriate for use as the extension for the chosen
output format.
.TP
.B %%
A single "%" character.
.P
If the \fITEMPLATE\fP argument is not specified, read group files are named
according to the template "\fB%*-%ID.%.\fP".
.P
The
.BI "-o " FILE
filename is expanded similarly, though \fB%XY\fP and \fB%#\fP are not useful
here as no particular read group is associated with this output file.
.SH LIMITATIONS
At present, all output files are opened simultaneously, so the number of
read groups that a file can be split into is limited by the process
limit on open file descriptors.
.SH SEE ALSO
.IR samcat (1)
