name: CI

on:
  push:
    branches: master
  pull_request:

jobs:
  build:
    name: ${{ matrix.compiler == 'g++' && 'GCC' || 'Clang' }} ${{ matrix.std }}
    runs-on: ${{ matrix.compiler == 'g++' && 'ubuntu' || 'macos' }}-latest
    strategy:
      matrix:
        compiler: [g++, clang++]
        std: [c++98, c++11, c++14, c++17, c++20, c++2b]
      fail-fast: false

    steps:
      - name: Check out cansam
        uses: actions/checkout@v4

      - name: Install Linux prerequisites
        if:   runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -q --no-install-recommends --no-install-suggests libboost-all-dev

      - name: Install macOS prerequisites
        if:   runner.os == 'macOS'
        run: |
          brew install boost
          echo "CPATH=$HOMEBREW_PREFIX/include" >> $GITHUB_ENV

      - name: Compile cansam
        run: |
          make -k "CXX=${{ matrix.compiler }} -std=${{ matrix.std }}"

      - name: Run tests
        run: |
          make test
